# Generated by Django 3.0.4 on 2020-04-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In_Progress', 'In Progress'), ('Postponed', 'Postponed'), ('Closed', 'Closed')], default='New', max_length=100),
        ),
    ]
